name: test-collector

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  test-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Test collector
        run: go test -v -exec sudo ./collector/
