name: test

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test collector
        run: go test -exec sudo -v ./collector/
